# Only trigger, when the build workflow succeeded
name: CI deploy
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate Namespace
      uses: okteto/namespace@master
      with:
        namespace: gpapacharalambous

    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: gpapacharalambous
        manifest: k8s.yaml

    - name: "Push changes"
      uses: okteto/push@latest
      with:
        namespace: gpapacharalambous
        name: hello-world